### ISSUE TITLE
How to install the plugin in linux

### ISSUE THREAD

**Issue by jw-star** [modheader/modheader#101]
I want to install the plugin on linux, but linux has no ui

**Comment by hao1300** [comment]
@jw-star - can you explain your use case? Why do you need to use ModHeader in a browser with no UI?

**Comment by jw-star** [comment]
> 

selenium  Unable to use plugin in headless mode

**Comment by hao1300** [comment]
@jw-star - can you use https://github.com/modheader/modheader_selenium for selenium instead?

**Comment by jw-star** [comment]
yes
