### ISSUE TITLE
[Bug] Add button does not work

### ISSUE THREAD

**Issue by tperich** [modheader/modheader#108]
Currently, when creating a new profile, one header field is added by default. When clicking the plus button on in the upper-right corner to add another header field, nothing happens.

Firefox 90.0

**Comment by hao1300** [comment]
@tperich I am not able to reproduce this. Are you able to inspect the popup to see if there is any error in the console?

**Comment by tperich** [comment]
@hao1300 It appears that the bug appears when you move the extension icon the the "more" menu by clicking customize in Firefox. I'll try to provide look into it once I have the time
