### ISSUE TITLE
Can not modify two headers with the same name

### ISSUE THREAD

**Issue by marsleezm** [modheader/modheader#113]
Hi I am trying to update the Set-Cookie header and looks like only the last Set-Cookie was updated.
I took a look at the source code and it looks like it's because you are using a map to store cookies by the name, so only the last header with that name will be modified and saved.
Could you confirm and fix the bug?

**Comment by hao1300** [comment]
@marsleezm - for modifying Set-Cookie, we have added support for it in ModHeader v4: https://docs.modheader.com/getting-started/modify-cookies.
