### ISSUE TITLE
lock tab?

### ISSUE THREAD

**Issue by bertt** [modheader/modheader#114]
Hi, 

I've got the impression button lock tab has disappeared in version 4? Is there maybe an alternative way to use modheader only on 1 browser tab?

Thanks

**Comment by TimToplak** [comment]
Now you can use tab filters:
![image](https://user-images.githubusercontent.com/23419877/167620702-248b42ec-34d1-40e8-942c-72c663965ceb.png)

**Comment by bertt** [comment]
ah ok thanks
