### ISSUE TITLE
Doesn't work on .*google.com sites

### ISSUE THREAD

**Issue by ssgao** [modheader/modheader#118]
First of all, thanks for the extension!

I noticed the extension stops working on anything related to google.com domain. Other domains work such as abc.com.

Is there a reason why?

Version installed: 4.0.10 from Chrome Store
Browser version 103.0.5060.114 (Official Build) (x86_64)

**Comment by hao1300** [comment]
I just tested and it is still modifying headers on www.google.com. What headers are you trying to modify? Do you have some filters setup?

Note that Google is using HTTP/3. It is not supposed to change the header definition, but maybe it affects some headers. I am not sure.
