### ISSUE TITLE
Feature Request: Add expiration timer that turns off a profile

### ISSUE THREAD

**Issue by haggs** [modheader/modheader#123]
We use ModHeader at my job, and often run into issues because we didn't realize ModHeader was active. I know there's a badge and this could just be considered user error, but have you considered adding a feature where you can set an expiration on a profile or an option to pause modheader after a time limit, maybe with a notification saying something like "Mod header timer expired, paused".

Thanks for all the hard work, I love this tool.

**Comment by hao1300** [comment]
@haggs - Thanks for the feature request suggestion. I will add it to the roadmap and tackle it in the coming weeks.

**Comment by hao1300** [comment]
@haggs - I have released ModHeader v4.0.15 with the initial version of Time Filter. It will cause the profile to expire when the time is reached. No notification yet, but will look into adding it in the future.

**Comment by haggs** [comment]
Wow, thanks Hao. I installed v4.0.15 but I'm not sure how to set the
expiration timer?
