### ISSUE TITLE
Underscores in request header keys are no longer working

### ISSUE THREAD

**Issue by EricMKaufman** [modheader/modheader#124]
![image](https://user-images.githubusercontent.com/1189011/189184844-4b57f5e9-b79f-442f-8d74-6281f53a60c2.png)

**Comment by hao1300** [comment]
@EricMKaufman - there is a bug in my website* which is not receiving headers with `_`. If you check the network panel, you will see that the `_` request header is being sent.

*My website is behind CloudFront and somehow CloudFront strips away `_` request header. I am not sure why yet.

**Comment by EricMKaufman** [comment]
Thanks @hao1300
