### ISSUE TITLE
Dynamic value does not work

### ISSUE THREAD

**Issue by Cdners** [modheader/modheader#57]
function does not work, the code is treated as a string

function({ url, oldValue }) { return 'World'; }
![image](https://user-images.githubusercontent.com/32647021/89028768-9302a780-d35f-11ea-96bf-46c4327361f2.png)

function({ url, oldValue }) { return '1.1.1.1'; }
![image](https://user-images.githubusercontent.com/32647021/89028705-7ebeaa80-d35f-11ea-8585-e413b809c1be.png)

function({ url }){ return Math.floor(Math.random() * 256) + "." + Math.floor(Math.random() * 256) + "." + Math.floor(Math.random() * 256) + "." + Math.floor(Math.random() * 256); }
![image](https://user-images.githubusercontent.com/32647021/89028836-aada2b80-d35f-11ea-95b2-e8ff16d53ac0.png)

**Comment by hao1300** [comment]
Thank you for reporting. It appears to be a recent regression. I am publishing a fix in version 3.1.9. Just waiting for Chrome Web Store approval.

**Comment by Cdners** [comment]
4.x版本,我测试还是无法使用“function()...”, 你能举个例子教我如何使用么

**Comment by Cdners** [comment]
Version 4.x, I still can't use "function()...", can you give me an example to teach me how to use it

**Comment by hao1300** [comment]
hi @Cdners . We replaced dynamic function evaluation with dynamic variables instead: https://docs.modheader.com/advanced/dynamic-value (Chrome and Firefox don't like us using eval() to run functions at runtime). Can you let me know the kind of dynamic values you need to generate? Is it something like a random value within a certain range would do?

**Comment by Cdners** [comment]
1. IPv4

2. IPv6

3. Random number

4. Random string

5. Random (string + number)

The first one is what I need most. Thank you~
Is the usage in the picture wrong?

<img width="1741" alt="image" src="https://user-images.githubusercontent.com/32647021/186657389-2e474f7d-1579-48ff-964d-ed00d77c8264.png">

**Comment by Cdners** [comment]
1. IPv4

2. IPv6

3. Random number

4. Random string

5. Random (string + number)

The first one is what I need most. Thank you~
The usage in the picture seems to be wrong
<img width="1721" alt="image" src="https://user-images.githubusercontent.com/32647021/186658301-9b6d3d0a-ee89-450e-acf5-e1eed2f3e32d.png">

**Comment by hao1300** [comment]
Are you using ModHeader 4.0.18 or above? I will add support for IPv4 in the next update.

**Comment by Cdners** [comment]
now is 4.0.17, I will upgrade to the latest version, thank you

**Comment by hao1300** [comment]
@Cdners , 4.0.20 has been released with support for `{{ip_v4}}`
