### ISSUE TITLE
Dropdown options for headers values

### ISSUE THREAD

**Issue by catalinColac** [modheader/modheader#63]
Hello,

Would it be possible that value fields could also be dropdowns with pre-defined values by the user?
It would really help keeping the profile clean when dealing with the same header but few too many different values.

**Comment by hao1300** [comment]
This feature will be fixed in ModHeader v4. Expecting to release it in mid-May.

**Comment by hao1300** [comment]
ModHeader v4 has been released. You can now customize autocomplete entries like this: https://docs.modheader.com/advanced/customize-autocomplete
