### ISSUE TITLE
[Feature request / Bug fix] Cannot modify multiple response headers with the same name 

### ISSUE THREAD

**Issue by ghost** [modheader/modheader#65]
There is no way to read all 'Set-Cookie' values, if the server decided to set more than one cookie. Only the last one can be read and modified.

Example:
![bug](https://user-images.githubusercontent.com/46346491/100236030-6d606600-2f2d-11eb-8255-9078d36687a2.PNG)

Am I missing something? Maybe a 'Set-Cookie[1,2,3]' accessor or something similar?
Or maybe access to the header object as the third parameter to the function?

Have a great day, and thanks for the awesome extension!

**Comment by hao1300** [comment]
I am adding support for set-cookie modification as a first class feature in ModHeader v4. Still doing some final testing since this is a major release. Expecting to release it in mid-May.

**Comment by hao1300** [comment]
Cookie modification is now supported in ModHeader v4. See documentation: https://docs.modheader.com/getting-started/modify-cookies
