### ISSUE TITLE
Security: Leak of Personal/Company Secrets in Export function

### ISSUE THREAD

**Issue by TheAxZim** [modheader/modheader#87]
### Summary

The following lines generate the shareable URL which users can then use to import a profile.

https://github.com/bewisse/modheader/blob/master/src/svelte/ExportDialog.svelte#L43-L45

The problem that I have with this (and businesses/personal users too) is that the encoded text could contain secrets.
It's not a problem if the users share the links with each other in a safe way.

But.... opening these links in the browser will send the request to `bewisse.com`
If bewisse.com is logging any of these requests, then they will have access to the secrets being shared. (e.g. api keys for test environments etc)

The user doesn't necessarily have to open the links in the browser either. Just sharing them on software such as slack (which tries to unfurl the links) will cause the secrets to be shared with `bewisse.com`

### Recommendation

Don't use URLs -> switch to something else like an encoded json blob. This still means that if users leak the encoded blobs, they expose their secrets, but at least they aren't leaking them to `bewisse.com` without realizing.

**Comment by hao1300** [comment]
There is always an option to choose between URL and JSON when exporting. You can just select the JSON format if it contains secrets that you don't want to be exposed.

**Comment by TheAxZim** [comment]
> There is always an option to choose between URL and JSON when exporting. You can just select the JSON format if it contains secrets that you don't want to be exposed.

Thats true, but I hope other users are aware that using URL sharing could expose their secrets in that case.

**Comment by hao1300** [comment]
We now export the profile to ModHeader on the server side instead of encoding it in the URL. The shareable URL is now `https://modheader.com/profile/*`. Users can change the exported profile visibility to make it not viewable by other users.

Although this does not change the fact that `modheader.com` still may have access to the underlying profile, it should at least give more controls to the users to manage the shared profile.
