### ISSUE TITLE
Redirect Pattern

### ISSUE THREAD

**Issue by signalwerk** [modheader/modheader#88]
I would like to redirect all URLs starting with `https://example.com/file.html?hash=` to localhost.

It should then catch  

`https://example.com/file.html?hash=1`
`https://example.com/file.html?hash=2`
...

I saw there are filters but from what I understand, I cannot use patterns for redirects right?

**Comment by signalwerk** [comment]
could we do a handlng like:

`https://example.com/file.html?hash=1` = current handling
`/https:\/\/example\.com\/file\.html\?hash=.*/` = regex-handling

**Comment by hao1300** [comment]
@signalwerk - I have committed a fix to support this: https://github.com/bewisse/modheader/commit/eacb9fb529856932550ab4a684d2090878dc6901. I don't know when Chrome Web Store will publish the new version, but it would generally be available within a week.

**Comment by hao1300** [comment]
The new version was published a while back. Closing this.
