### ISSUE TITLE
Make flyout window resizable

### ISSUE THREAD

**Issue by jockie** [modheader/modheader#91]
We're using ModHeader to test our application with quite a few different user profiles. The small window of the application makes it harder to distinguish between the different header values. Even the comment field does not ease that. Making the flyout window resizable would be a great solution to that issue.

**Comment by hao1300** [comment]
Hi @jockie - thanks for the suggestion, and apologize for the late reply. I am finally getting back to maintaining ModHeader actively. I will look into supporting this use case in the next version.

**Comment by hao1300** [comment]
This will be fixed in ModHeader v4. Expecting to release it in mid-May.

**Comment by hao1300** [comment]
Hi @jockie, ModHeader v4 has been released. You can now open ModHeader in a full tab view: https://docs.modheader.com/advanced/large-editor
