### ISSUE TITLE
Feature Request: filter to apply to all requests in a tab as long as the tab URl matches pattern

### ISSUE THREAD

**Issue by bersbersbers** [modheader/modheader#93]
I have two GitHub accouts, one for everything else and one for access to one private repo (to which the first account does not have access). I have managed to set a cookie rule and a filter so that when I am at https://github.com/private/private, I am accessing it through the proper account without having to enable or disable a filter at all. All other repos I can access using my normal account. This is great.

However, actions such as commenting go through https://github.com/settings/replies?context=issue to which my filter does not apply. I would like the filter to apply to *behind-the-scenes* requests as long as the TAB url matches the filter pattern. Is that possible?

**Comment by bersbersbers** [comment]
Yes, I think you could say it that way. As soon you navigate to some URL in a tab which matches a filter all subsequent connections in that tab should use this filter's settings. #89 looks very similar indeed.

**Comment by hao1300** [comment]
OK, merging issue with https://github.com/modheader/modheader/issues/89
