### ISSUE TITLE
Can I access profile content during runtime？

### ISSUE THREAD

**Issue by Leecason** [modheader/modheader#97]
I now want to get the Request header during runtime and show it on the page, how can I do this ? thx

**Comment by Leecason** [comment]
> @Leecason - can you explain your use-case? Are you trying to show the request headers to your own server on your own page in production? Or do you need to see request headers for any network request on any page for development purpose?

In the production environment used for testing, different headers will access different code, and show the added headers on the page is a quick way to differentiate the environment. You don't have to click the browser extension.

**Comment by hao1300** [comment]
@Leecason - I don't think I will be including this feature in ModHeader. This sounds like something specific to your server. You may want to consider building that functionality to show additional debugging info when certain header is set.
